# netlify.toml

# Build settings
[build]
  command = "npm run build"  # Change this to your build command
  publish = "dist"           # Change this to your build output directory

# Redirects settings (optional, adjust as needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers settings (optional, adjust as needed)
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
